USE [MIS]
GO

/****** Object:  Table [FC].[WCT_CUSTOMFIELD]    Script Date: 5/21/2018 10:43:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [FC].[WCT_CUSTOMFIELD](
       [BUSS_DATE] [datetime] NULL,
       [KEY] [varchar](9) NOT NULL,
       [Cust_Name] [varchar](255) NOT NULL,
       [CIF_Customer] [varchar](255) NOT NULL,
       [Application_Type] [varchar](255) NOT NULL,
       [Sector_Industry] [varchar](255) NOT NULL,
       [RM_Total_Existing_Cash_Loan_Amt_IDR] [numeric](38, 4) NOT NULL,
       [RM_Total_Inc/Dec_Cash_Loan_Amt_IDR] [numeric](38, 4) NOT NULL,
       [RM_Total_Limit_Cash_Loan_Amt_IDR] [numeric](38, 4) NOT NULL,
       [Facility_1_Type] [varchar](255) NOT NULL,
       [Facility_2_Type] [varchar](255) NOT NULL,
       [Facility_3_Type] [varchar](255) NOT NULL,
       [Facility_4_Type] [varchar](255) NOT NULL,
       [Facility_5_Type] [varchar](255) NOT NULL,
       [Facility_6_Type] [varchar](255) NOT NULL,
       [Facility_7_Type] [varchar](255) NOT NULL,
       [Facility_8_Type] [varchar](255) NOT NULL,
       [Facility_9_Type] [varchar](255) NOT NULL,
       [Facility_10_Type] [varchar](255) NOT NULL,
       [SME_Region] [varchar](255) NOT NULL,
       [Area] [varchar](255) NOT NULL,
       [Assign_to_BM] [varchar](255) NOT NULL,
       [Reporter] [varchar](255) NOT NULL,
       [RM_BI_Code] [varchar](255) NOT NULL,
       [SME_RM_Branch] [varchar](255) NOT NULL,
       [Referral] [varchar](255) NOT NULL,
       [Sales_Program_Code] [varchar](255) NOT NULL,
       [Cabang_Pemberi_Referral] [varchar](255) NOT NULL,
       [Nama_Pemberi_Referral] [varchar](255) NOT NULL,
       [AO_Cd_Pemberi_Referral] [varchar](255) NOT NULL,
       [Staff_ID_Pemberi_Referral] [varchar](255) NOT NULL,
       [STATUS] [varchar](255) NOT NULL,
       [AGING] [int] NOT NULL,
       [CREATED] [varchar](10) NULL,
       [DUW_Received_Date] [varchar](10) NULL,
       [TL_CA_Received_Date] [varchar](10) NULL,
       [Approval_Date] [varchar](10) NULL,
       [Signing_Date] [varchar](10) NULL,
       [Assign_to_DUW] [varchar](255) NOT NULL,
       [Assign_to_CA_1] [varchar](255) NOT NULL,
       [Assign_to_CA_2] [varchar](255) NOT NULL,
       [Assign_to_CA_3] [varchar](255) NOT NULL,
       [System_Decision] [varchar](255) NOT NULL,
       [DA_Decision] [varchar](255) NOT NULL,
       [Cancelled_Date] [varchar](10) NULL,
       [Application_Cancel_Reason] [varchar](255) NOT NULL,
       [Application_Cancel_Remarks] [varchar](255) NOT NULL,
       [Application_Decline_Date] [varchar](10) NULL,
       [Decline_Reason] [varchar](255) NOT NULL,
       [Signing_Cash_Loan_Amt_IDR] [varchar](255) NOT NULL,
       [Facility_Fee_Amt] [varchar](255) NOT NULL,
       [Admin_Fee_Amt] [numeric](18, 2) NOT NULL,
       [Pre_Screen_Flag] [varchar](255) NOT NULL,
       [Rework_from_CA_1_to_RM] [varchar](255) NOT NULL,
       [Rework_from_DUW_to_RM] [varchar](255) NOT NULL,
       [Rework_from_CA_2_to_RM] [varchar](255) NOT NULL,
       [Rework_from_CA_3_to_RM] [varchar](255) NOT NULL,
       [Rework_from_DA_to_CA] [varchar](255) NOT NULL,
       [Rework_from_DA_to_DUW] [varchar](255) NOT NULL,
       [Rework_from_DA_to_RM] [varchar](255) NOT NULL,
       [Rework_from_DUW_to_LSS_(Pre-Screen)] [varchar](255) NOT NULL,
       [Rework_from_LSS_(SUL_Completion)_to_RM] [varchar](255) NOT NULL,
       [Rework_from_LSS_(Signing_Preparation)_to_CA] [varchar](255) NOT NULL,
       [Rework_from_LSS_(Signing_Preparation)_to_DA] [varchar](255) NOT NULL,
       [Rework_from_LSS_(Signing_Preparation)_to_DUW] [varchar](255) NOT NULL,
       [Rework_from_LSS_(Signing_Preparation)_to_RM] [varchar](255) NOT NULL,
       [RM_Decline_Reason] [varchar](255) NOT NULL,
       [System_Decision_Decline_Reason] [varchar](255) NOT NULL,
       [CA_1_Decline_Reason] [varchar](255) NOT NULL,
       [CA_2_Decline_Reason] [varchar](255) NOT NULL,
       [CA_3_Decline_Reason] [varchar](255) NOT NULL,
       [BM_or_DA_Received_Date] [varchar](10) NULL,
       [Disbursement_Date] [varchar](10) NULL,
       [Assign_to_DA] [varchar](255) NOT NULL,
       [Assign_to_BM_or_DA] [varchar](255) NOT NULL,
       [Renewal_Type] [varchar](255) NOT NULL,
       [Counter_Interest_Rate] [varchar](255) NOT NULL,
       [Take_Over] [varchar](255) NOT NULL,
       [Take_Over_From] [varchar](255) NOT NULL,
       [DUW_Auto_Approved_Cash_Loan_Amt_IDR_(Inc/Dec_Limit)] [numeric](18, 2) NULL,
       [DA_Approved_Cash_Loan_Amt_IDR_(Inc/Dec_Limit)] [numeric](18, 2) NULL,
       [Pre_Screen_Request_Date] [varchar](10) NULL,
       [LSS_(SUL_Completion)_Received_Date] [varchar](10) NULL,
       [Loan_Ops_Received_Date] [varchar](10) NULL,
       [Final_Liability_Limit] [varchar](255) NOT NULL,
       [Phase] [varchar](9) NOT NULL,
       [Formula] [int] NOT NULL,
       [Aging_in_Respective_Phase] [int] NULL,
       [Aging_E2E] [int] NULL,
       [Amount] [numeric](18, 2) NULL,
       [Aging_in_CA_in_Phase_2] [int] NULL,
       [Aging_E2E_Bucket] [varchar](14) NOT NULL,
       [Aging_Respective_Phase_Bucket] [varchar](14) NOT NULL,
       [Aging_Respective_Other_Bucket] [varchar](14) NOT NULL,
       [Phase_C] [varchar](7) NOT NULL,
       [Decline_Reason_D] [varchar](255) NOT NULL,
       [Amount_C] [numeric](18, 2) NULL,
       [Phase_D] [varchar](7) NULL,
       [Productivity Type] [varchar](100) NULL,
       [Facility 1 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 1 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 2 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 2 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 3 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 3 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 4 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 4 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 5 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 5 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 6 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 6 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 7 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 7 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 8 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 8 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 9 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 9 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 10 Increase/Decrease Cash Loan Limit] [numeric](38, 4) NULL,
       [Facility 10 Existing Cash Loan Limit] [numeric](38, 4) NULL,
       [FirstDt_DUW] [datetime] NULL,
       [RM_Decline_Date] [datetime] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
